### ISSUE TITLE
Automating all pair-wise comparisons across multiple sessions

### ISSUE THREAD

**Issue by catubc** [ransona/ROIMatchPub#2]
Hello

Thanks so much for this package, we have started to use it and it seems pretty useful.
We have a question about how to automate - or extend your code - to automatically compare all pairs of cells across multiple days.

For example, I have 4 recorded sessions (e.g. across 4 different days) and would like to match cells across all days-not just pairs of days.  For this I would have to compare:
- sess 1 vs. sess 2
- sess 2 vs. sess 3  
- sess 3 vs. sess 4  
- sess 1 vs. sess 3    <---- this is redundant
- sess 1 vs. sess 4    <---- this is redundant
- sess 2 vs. sess 4    <---- this is redundant

I would like to avoid redoing redundant sessions which grow exponentially in number with the number of sessions.  For 10 sessions, I would need to do 9 manual matches, but then another 25-30 because of the redundant matching.

What do you recommend I could do here? Is it possible to save the transformation masks between pairs of sessions and then combine them offline?

Any advice is appreciated.

Thanks so much, 

[EDIT]: I do see there is a "comparisonMatrix" array in the roiMatchData.mat file.  Was the intended use of this value to track multi-session alignment?

**Comment by marysethomas** [comment]
Hi @catubc, I am just a user (not the creator), but you can load more than 2 sessions into a single match file (just keep clicking 'Add Experiment'). I haven't tested the limits of this so I don't know how it would perform with many sessions, but you can give it a try. Good luck!

**Comment by catubc** [comment]
Ah, super, I was wondering. Ok, great, will try.
So is anyone still working on this code base then!?

**Comment by marysethomas** [comment]
That's a good question - I don't think so because the code hasn't been updated for a few years.
